name: Auto Commit & Update Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Auto Commit for Green Squares
        run: |
          echo "$(date) - Auto commit to keep GitHub streak alive" >> commit.log
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add commit.log
          git commit -m "chore: daily auto-commit $(date)"
          git push

      - name: Update GitHub Stats in README
        run: |
          sed -i "s|![GitHub Stats](.*)|![GitHub Stats](https://github-readme-stats.vercel.app/api?username=esteficodes&show_icons=true&theme=dark&cache_seconds=86400)|" README.md
          git add README.md
          git commit -m "chore: update GitHub stats $(date)" || echo "No changes to commit"
          git push || echo "No changes to push"
